--
-- Generated by Raider.IO on 2024-09-01T06:15:47Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 4812,
        ["instance_map_id"] = 631,
        ["lfd_activity_ids"] = { 1110, 1111, 1255, 1264 },
        ["name"] = "Icecrown Citadel",
        ["shortName"] = "ICC",
    },
    [2] = {
        ["id"] = 4987,
        ["instance_map_id"] = 724,
        ["lfd_activity_ids"] = { 1108, 1109, 1256, 1265 },
        ["name"] = "The Ruby Sanctum",
        ["shortName"] = "RS",
    },
    [3] = {
        ["id"] = 5094,
        ["instance_map_id"] = 669,
        ["lfd_activity_ids"] = {  },
        ["name"] = "Blackwing Descent",
        ["shortName"] = "BWD",
    },
    [4] = {
        ["id"] = 5334,
        ["instance_map_id"] = 671,
        ["lfd_activity_ids"] = {  },
        ["name"] = "The Bastion of Twilight",
        ["shortName"] = "BOT",
    },
    [5] = {
        ["id"] = 5638,
        ["instance_map_id"] = 754,
        ["lfd_activity_ids"] = {  },
        ["name"] = "Throne of the Four Winds",
        ["shortName"] = "TOTFW",
    },
}
